### ISSUE TITLE
Error running python 'clip_prepro_feats.py'

### ISSUE THREAD

**Issue by vbursztyn** [j-min/CLIP-Caption-Reward#5]
Hello,

I'm encountering an error (further below) when running:
`python scripts/clip_prepro_feats.py --input_json data/dataset_coco.json --output_dir data/cocotalk --images_root datasets/COCO/images --model_type RN50`

Which throws:
`File "scripts/clip_prepro_feats.py", line 117, in main
    tmp_att, tmp_fc = model.encode_image(image)
(…) query should be unbatched 2D or batched 3D tensor but received 4-D query tensor`

I have followed the steps in the README, and the line that I'm running is the exact same one from the README. My installation includes:
`torch==1.12.0`
`torchvision==0.13.0`
`clip @ git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1`

I can run the steps that come before (text processing) and after (visual feature extraction for CLIP-S) without problems.

Would you have any idea of what is wrong here? Thank you in advance for any pointers!

**Comment by j-min** [comment]
Hi @vbursztyn,

Could you please run the inference [colab](https://colab.research.google.com/github/j-min/CLIP-Caption-Reward/blob/main/Inference_example.ipynb) and check if you still face the error from the line `tmp_att, tmp_fc = clip_model.encode_image(image)`? Since the line works on the colab, checking the details such as image input and other package versions might help you find what the issue is.

**Comment by vbursztyn** [comment]
Thank you very much, @j-min. It's fixed! For reference, here's the reason:

I had taken the liberty of installing CLIP from OpenAI's repo, and for some reason it was causing this error. Uninstalling CLIP fixed it.
